### ISSUE TITLE
Should `_site` exist?

### ISSUE THREAD

**Issue by jamietanna** [DDDEastMidlandsLimited/dddem-web#102]
### Describe the bug

I noticed, while contributing #101, that there's an `_site` folder in the repo.
Is that meant to be there, as it seems to be a duplicate of a number of files
in the top-level folder in the repo?

**To Reproduce**

Steps to reproduce the behaviour:

* Open [_site](https://github.com/DDDEastMidlandsLimited/dddem-web/tree/master/_site)
* Notice that this includes a number of files that already exist top-level

**Reproduces how often:**

100%

**Expected behaviour**

It does not exist

**Screenshots**

N/A

**Comment by wordshaker** [comment]
Haha! Oops. That should be in the gitignore.
