### ISSUE TITLE
Enhancement: Improve the layout of our links

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#103]
### Describe the feature

* We aren't UXers... in fact, two of us hardly do any front-end. We would love to find a way to make the content of our site more navigable and user-friendly.

### Advantages

* People will be able to find the information they need and enjoy using our site.

**Comment by molly7657** [comment]
Hi @wordshaker ! I'm happy to take a look at your site and add some UX design. What were you thinking?

**Comment by RizBizKits** [comment]
@wordshaker, claiming this, please. i'll see how much i can get this moved along.. :)
