### ISSUE TITLE
Fix: Initial click on About from home page broken

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#110]
### Describe the bug

* Initial click goes to `https://www.dddeastmidlands.com/#` instead of displaying the drop-down of links

**To Reproduce**

* Go to homepage [https://www.dddeastmidlands.com](https://www.dddeastmidlands.com)
* Click About

**Reproduces how often:**

100%. 

If you go to another page then click "About" it works 

**Expected behaviour**

About should display the drop down of information pages.

**Comment by ferfabricio** [comment]
Hi @wordshaker,

I can't reproduce this on my computer.

SO: Mac OS Mojave (10.14.6)
Browsers:
Firefox Version 69.0.3 (64-bit)
Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Safari Version 13.0.2 (14608.2.40.1.2)

**Comment by wordshaker** [comment]
Hmm... It's not happening on my machine anymore either. 

Maybe a deployment blip. Sorry!
