### ISSUE TITLE
Enhancement: Create talk "shopping basket"

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#111]
### Describe the feature

The talks presented on at DDD East Midlands are voted on by attendees. We display only the title and description of submitted talks - and attendees vote on which ones they wish to see

The current process is a filtered list and then a google form to submit your top 8 in.

It would be great to have an amazon style "shopping basket" where you could add and remove talks from your basket until you have your final shortlist you want to submit. 

### Advantages

Easier voting process
Nicer UX

**Comment by Jam52** [comment]
I think I could give this one a go!

**Comment by wordshaker** [comment]
All yours
