### ISSUE TITLE
Enhancement: Enabled caching of basic imagery like header and footer in Service Worker

### ISSUE THREAD

**Issue by johnnolan** [DDDEastMidlandsLimited/dddem-web#115]
### Describe the feature

Add the header and footer images to the SW cache for a more speedy result

### Advantages

Prepares for a better offline experience

#### Acceptance Criteria

Images are loaded from the SW and reloaded if they change

- [ ]

**Comment by rgroves** [comment]
I'd like to take this on if no one is currently working on it.

**Comment by paolapog** [comment]
Hi @johnnolan ! is this still an issue?  If it is so, I'd like to try to help you with the SW: I’m a first-time contributor but I worked with SW in my actual company. Thanks!
