### ISSUE TITLE
Bug: Twitter Logo is not correct

### ISSUE THREAD

**Issue by sundaram-sharma** [DDDEastMidlandsLimited/dddem-web#1362]
### Describe the bug

Recently, the Twitter logo and name have been changed since July 2023 ( as per Wikipedia) and it is not reflected on the website.

**To Reproduce**

1. Go to 'https://dddeastmidlands.com/'
2. Scroll down to the footer of the webpage
4. See the outdated Twitter ( X ) logo 

**Reproduces how often:**

Every time we open the website, it displays on several web pages

**Expected behavior**

on every page of the website, the updated logo should display

**Screenshots**

<img width="301" alt="image" src="https://github.com/DDDEastMidlandsLimited/dddem-web/assets/98935619/c834a3b5-747a-4e49-9616-cda775ccfb05">

<img width="1268" alt="image" src="https://github.com/DDDEastMidlandsLimited/dddem-web/assets/98935619/22587d06-a7d8-44cc-a575-35e8b506b3c6">

**Comment by sundaram-sharma** [comment]
Hi developers, I just fixed the issue and created the pull request. I request you to please review and accept it if it passes. Thanks

**Comment by shaund16** [comment]
@sundaram-sharma looks like this has been handled. I pulled up the site and see the changes. This issue can be closed.
