### ISSUE TITLE
Hacktober Feature Request: Autumn-themed header for the website

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#165]
### Describe the feature

- Create an Autumn-themed header for the website and add it to the assets folder.

### Advantages

- Fun seasonal headers.

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Autumn-themed header created
- [ ] Autumn-themed header added to assets

**Comment by AmeyaJain-25** [comment]
I would like to work on this.
Please assign me.

**Comment by AmeyaJain-25** [comment]
Can you describe more about the theme to be added

**Comment by wordshaker** [comment]
Hi @AmeyaJain-25 

A banner with anything autumn based. Pumpkins, fall leaves, Halloween etc. and associated colours

**Comment by AmeyaJain-25** [comment]
Ok @wordshaker ,
Thanks for assigning.

**Comment by wordshaker** [comment]
Hacktober is now finished for this year
