### ISSUE TITLE
Hacktober Feature Request: Pride-themed header for the website

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#166]
### Describe the feature

- Create a Pride-themed header for the website and add it to the assets folder.

### Advantages

- Fun seasonal headers.

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Pride-themed header created
- [ ] Pride-themed header added to assets

**Comment by AmeyaJain-25** [comment]
Is this issue solved.
If not, can i work on this. Please assign me

**Comment by wordshaker** [comment]
You can always add another one 😄 It's nice to have choice

**Comment by AmeyaJain-25** [comment]
Okay, thanks @wordshaker

**Comment by wordshaker** [comment]
Closing as hacktober has ended for this year
