### ISSUE TITLE
Hacktober Feature Request: Automatically change header based on date

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#167]
### Describe the feature

Header changes based on the month of the year. The following issues have asked for people to create themed headers for the website:

- #166 Pride header (June)
- #165 Autumn header (September - November)
- #164 Winter header (December)

This issue asks that the header is set to these themes during set time periods

### Advantages

- Automatically changing the header means no one has to do it manually.

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Header changes based on the month of year.

**Comment by roygrv21** [comment]
Hi @wordshaker, Can I work on this issue?

**Comment by wordshaker** [comment]
It's all yours @roygrv21 😄

**Comment by roygrv21** [comment]
I am done with the changes, shall I create the PR with a dummy autumn header, which could be later replaced by the one which is going to be addressed in #165 ?

**Comment by wordshaker** [comment]
Yes please @roygrv21

**Comment by roygrv21** [comment]
@wordshaker I guess this issue could be closed, as the PR is already merged.
