### ISSUE TITLE
Hacktober Feature Request: Add Accessibility tests

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#172]
### Describe the feature

- Add pa11y to CI build to demonstrate how changes impact accessibility

### Advantages

- Helps the repo keep an accessibility focus

## Links

- [pa11y ](https://github.com/pa11y/pa11y-ci)

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Pally runs on every PR build

**Comment by johnnolan** [comment]
Awesome idea, happy to have a play with this one

**Comment by wordshaker** [comment]
All yours 😄
