### ISSUE TITLE
Bug: Banner images on main information page are too large

### ISSUE THREAD

**Issue by johnnolan** [DDDEastMidlandsLimited/dddem-web#177]
### Describe the bug

On the page https://www.dddeastmidlands.com/information/main-page/ our banner images are too big for the site. Currently the page is 4.3mb in size. 

We need to do the following.

- Go through each banner image and resize relatively to a max of 940px wide.
- Run each image through tinypng to remove any excess data

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'https://www.dddeastmidlands.com/information/main-page/'
2. Open chrome dev tools
3. Go to the performance tab
4. Look at the size of the images before and after

**Reproduces how often:**

100%

**Expected behaviour**

- Sizes to be dramatically reduced. 
- looks the same on mobile, tablet and desktop sizes

**Screenshots**

None

**Comment by aknrg77** [comment]
Hi I would like to work on this issue

**Comment by wordshaker** [comment]
All yours @aknrg77

**Comment by piratelicorne** [comment]
Hi, If this still open, I can help :)

**Comment by sambarnes90** [comment]
I'm happy to take this on if you want to assign me @wordshaker 😄 

I've been through this process a few times so should be able to get it done fairly easily.

*Top Tip* - InfranView very good for bulk resizing images at a ratio.

**Comment by wordshaker** [comment]
It's all yours @sambarnes90!
