### ISSUE TITLE
Hacktober Feature Request: Add to the Hacktober Page

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#181]
### Describe the feature

- Add your name and why you like the East Midlands tech scene to the Hacktober page as per the instructions on the [Hactober Page](https://www.dddeastmidlands.com/2020/hacktober/)

- This can be picked up by multiple people

### Advantages

- Gives us an awesome lists of reasons why people like to live and work in the East Midlands, UK

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Your name and reason why you like the east midlands tech scene is added to the list at the bottom of the page

**Comment by ChiragBolakani** [comment]
Hey,  Should I add one review to it? I don't have a twitter account though. I'm participating in hacktoberfest. @wordshaker

**Comment by wordshaker** [comment]
@ChiragBolakani a review without twitter link is fine 👍🏼

**Comment by ChiragBolakani** [comment]
@wordshaker Hey I have made the changes please have a look at my pull request. I'll try to contribute more to this repo. Thanks.

**Comment by JukMR** [comment]
Hi! I would like to make my contribution to this! Could I make a PR? I am also participating in hacktoberfest.

**Comment by wordshaker** [comment]
Add anything you like to this :)

**Comment by wordshaker** [comment]
Hacktober is finished for this year
