### ISSUE TITLE
Hacktober Feature Request: Install Google Analytics

### ISSUE THREAD

**Issue by johnnolan** [DDDEastMidlandsLimited/dddem-web#189]
### Describe the feature

We currently use [https://www.npmjs.com/package/react-ga](https://www.npmjs.com/package/react-ga) to implement Google Analytics tracking on our site. However, we require now the gtag implementation to add new functionality.

In [analytics.js](https://github.com/DDDEastMidlandsLimited/dddem-web/blob/main/utils/analytics.js) we need to replace the npm library in here with [https://www.npmjs.com/package/react-gtm-module](https://www.npmjs.com/package/react-gtm-module) and update the code within the functions to use this new library for tracking page views and events.

The Analytics ID is already in the file and should be used for this too. The readme on how to initialise and replicate the existing functionality is also in the npm docs.

### Advantages

Be able to plug in new features that take advantage of gtag.

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

All existing tracking functionality still works - [ ]
react-ga is removed from the package.json file - [ ]

**Comment by JipSterk** [comment]
I would like to implement this. but when i forked & downloaded the repo. i found [analytics](https://github.com/DDDEastMidlandsLimited/dddem-web/blob/main/utils/analytics.js) is feature already implemented? also the tracking code you provided in your comment is different then the one inside the codebase

**Comment by johnnolan** [comment]
Hi @JipSterk you are right, forgive me, I was looking for the gtag script and couldn't find it. I am going to rewrite the ticket to use a npm library that will replace the functions in the analytics file. Sorry for the confusion, hopefully it makes more sense now.
