### ISSUE TITLE
Feature Request: Change images to add image auto optimisation

### ISSUE THREAD

**Issue by johnnolan** [DDDEastMidlandsLimited/dddem-web#192]
### Describe the feature

We want to swap out our images so we can better support those who have poorer devices or bandwidth. We want to ideally do this automatically using a package like https://github.com/cyrilwanner/next-optimized-images so that we can be sure we are optimised as much as possible automatically. 

### Advantages

Speed, SEO and accessibility wins

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] All images have been converted to srcset that are appropriate
- [ ] All background-images are converted

**Comment by Jam52** [comment]
Hi! I think I understand what to do here, after installing and configuring the package we have to update all images to use src={require('./pathname...')} is that correct?
