### ISSUE TITLE
Bug: Split links/Images on the Information Main Page

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#211]
### To Reproduce

1. Visit the information page on desktop: https://www.dddeastmidlands.com/information/main-page/

### Reproduces how often:

100% of the time

### Expected behaviour

Images don't split across columns

### Screenshots

![image](https://user-images.githubusercontent.com/13496774/110245621-f4c16a80-7f5b-11eb-9bfa-3cfd7d7c7bdc.png)

**Comment by johnnolan** [comment]
@wordshaker is this still an issue, just looked and I can't reproduce

**Comment by wordshaker** [comment]
I think I "fixed" it by removing one of the links. If there is an odd number on the page it still breaks 😄  

I'm a dirty hacker sometimes...

**Comment by Jam52** [comment]
How do you navigate to this page? Currently the dropdown in the nav will take you to the individual pages not the overall page.

**Comment by wordshaker** [comment]
I removed it 😂 as it was too annoying
