### ISSUE TITLE
Feature Request: Change footer to use fontawesome

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#241]
### Describe the feature

Change the social links which are now text links, to use fontawesome or a similar package that can display logos instead of text

### Advantages

- Makes footer smaller

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] the links in the footer are changed to use fontawesome or similar

**Comment by nicoolel** [comment]
Hello, is this issue still available? If so, may you please assign it to me?

**Comment by wordshaker** [comment]
Hi @nicoolel, it's all yours 😄 Lets us know if you need any assistance.
