### ISSUE TITLE
Bug: Fix ES Lint Run

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#376]
### Describe the bug

The ES Lint Run is erroring out 

![Screenshot 2021-06-10 at 16 04 56](https://user-images.githubusercontent.com/13496774/121549255-9ba71e00-ca05-11eb-9d84-2e91f50223cf.png)

https://github.com/DDDEastMidlandsLimited/dddem-web/runs/2771038278?check_suite_focus=true

**To Reproduce**

- Go to https://github.com/DDDEastMidlandsLimited/dddem-web/runs/2771038278?check_suite_focus=true

**Reproduces how often:**

- 100%

**Expected behaviour**

Run succeeds

**Screenshots**

N/A

**Comment by wordshaker** [comment]
@johnnolan maybe one for you when you are bored?

**Comment by johnnolan** [comment]
The fix for this seems to be removing `event` as a param here https://github.com/DDDEastMidlandsLimited/dddem-web/blob/main/components/Navigation.js#L63 will try and look at this soon

**Comment by johnnolan** [comment]
Fix incoming
