### ISSUE TITLE
Bug: Tab behaviour broken on Header

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#415]
### Describe the bug

The tabbing behaviour throws an error on every page on the Header element

#### To Reproduce

Steps to reproduce the behaviour:

Tested on Chrome

1. Go to any page on the website
2. tab through past the header
3. An error will show

#### Reproduces how often:

100%

#### Expected behaviour

No errors shown when tabbing through a page

**Screenshots**

![image](https://user-images.githubusercontent.com/13496774/124464316-f7a65d80-dd8b-11eb-98d8-07f0c911fdf6.png)

**Comment by johnnolan** [comment]
I think this is within the react bootstrap component but will dig deeper

**Comment by johnnolan** [comment]
It would be nice to remove bootstrap completely if possible to reduce asset size and dependencies but would need to research to keep the same behaviour and accessibility

**Comment by wordshaker** [comment]
@johnnolan whatever your fine front end guru thinks is best. Btw, LOVE the progressive enhancement on this site. Tried using it with JS disabled the other day and it was an ok experience!
