### ISSUE TITLE
Feature Request: Enhance Speaker grid 

### ISSUE THREAD

**Issue by Jam52** [DDDEastMidlandsLimited/dddem-web#442]
### Describe the Enhancement

Enhance the speaker grid page by adding names and topic title.
Add keynote callout for keynote speaker.
Create a component for the speaker cards to reduce code.

### Advantages

Make exploring the speakers and topics easier.
Creating a component should help code readability.

#### Acceptance Criteria

Speaker cards contain correct name and topic title
Callout for keynote speaker looks integrated

**Comment by astannard** [comment]
Not sure how you tackle a request but here is my work, I've create a component and added in the speaker names and their talk titles. The component will make it easier for further enhancement anyway: https://github.com/DDDEastMidlandsLimited/dddem-web/pull/521

**Comment by Evie-Skinner18** [comment]
Hi @Jam52 , what do you mean by 'callout for keynote speaker'?

**Comment by wordshaker** [comment]
Completed by @astannard
