### ISSUE TITLE
Enhancement: Add Frontend Performance Metrics

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#48]
### Describe the feature

We want to be able to see any Javascript errors and page metrics of the site.

To do this we can use the npm library https://www.npmjs.com/package/@ministryofjustice/opg-performance-analytics

The readme contains the setup instructions, I believe it would sit within the `_app.js` file alongside the other GA code.

This will send data to Google Analytics that we can monitor over time.

We don't currently have Google Analytics installed either which would need to be done first. The ticket for this is here #189

**Comment by piratelicorne** [comment]
I would like to know what is this about, maybe I can help.

**Comment by wordshaker** [comment]
@johnnolan anything you would like here?

**Comment by johnnolan** [comment]
I have updated the description to be more explicit that should hopefully help. It is blocked by #189 but both should be straight forward. Always happy to help through with this so feel free to tag me in any comments or PRs @piratelicorne and I will help any way I can.
