### ISSUE TITLE
Accessibility: Add Tabbing Behaviour For Nav And Links

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#49]
### Describe the feature

We would like our site to be accessible and useable to as many people as we can achieve. As part of this initiative, we would like the site to be navigable mouse-free.

### Advantages

* Increases the audience for DDD East Midlands

* Helps people access the information they may need about the event

#### Acceptance Criteria

- [ ] All links can be accessed without using a mouse

#### Resources

- [Using tabindex](https://developers.google.com/web/fundamentals/accessibility/focus/using-tabindex)

**Comment by KaylaKremer** [comment]
I can work on this!

**Comment by KaylaKremer** [comment]
I just submitted the PR for this issue: https://github.com/DDDEastMidlandsLimited/dddem-web/pull/95

**Comment by lkreimann** [comment]
I suggest removing the label "up-for-grabs" :)

**Comment by wordshaker** [comment]
Changes merged in
