### ISSUE TITLE
HACKTOBER: Add your selfie

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#499]
### Describe the feature

- At the DDD East Midlands Conference add your selfie to our Hacktober page

### Advantages

- We can see who is contributing at the event
- In with a chance to win a prize

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Follow the instructions on https://www.dddeastmidlands.com/2021/hacktober/

**Comment by Manishgupta200** [comment]
Thanks for assigning
