### ISSUE TITLE
Bug: Remove sidescroll bar

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#52]
### Describe the bug

Since introducing a dropdown nav, a sideways scroll bar has been present on the live site. We would like for this to be removed.

**Screenshots**

![image](https://user-images.githubusercontent.com/13496774/54538179-b657cd00-498b-11e9-9797-de0c5d5a23e1.png)

**Comment by zurda** [comment]
Can I look into this, and try to resolve it?

**Comment by HoraceSupertramp** [comment]
@zurda, need any help?

**Comment by teisenhower** [comment]
Is this still open for fixing? I think I have a solution ready to go for this if it's alright that I hop in. 

Thanks

**Comment by zurda** [comment]
@HoraceSupertramp , @teisenhower : Not sure. I haven't heard back so I'm retracting my suggestion.

**Comment by johnnolan** [comment]
Hi all, missed these comments, I cannot reproduce for some reason so happy for someone to put a fix forward! Let me know if I can help at all

**Comment by wordshaker** [comment]
Sorry all, I'be been away. Throw a `in progress` label on it, assign yourself and it's all yours @zurda.
@johnnolan is the person to talk to if you get stuck 👍 he's our website guru.

**Comment by wordshaker** [comment]
Sorry that we took too long to get back form you @zurda - it's open if you change your mind :

**Comment by blzn50** [comment]
Hi, @johnnolan, @wordshaker  I have created the fix for the sidescroll issue. Can I create the pull request if it is still available?

**Comment by wordshaker** [comment]
All merged in. Thanks @blzn50

**Comment by wordshaker** [comment]
Fixed in https://github.com/DDDEastMidlandsLimited/dddem-web/pull/61
