### ISSUE TITLE
Bug: dddeastmidlands.com not accessible via IE

### ISSUE THREAD

**Issue by RichBenner** [DDDEastMidlandsLimited/dddem-web#53]
https://www.dddeastmidlands.com/ is not accessible via Internet Explorer

**To Reproduce**

Steps to reproduce the behaviour:

1. Open IE
2. Attempt to access https://www.dddeastmidlands.com/
3.You'll get the 'An unexpected error has occurred' error

What percentage of the time does it reproduce, if you know? 100%

**Expected behaviour**

It would be nice if it worked

**Screenshots**

![image](https://user-images.githubusercontent.com/20068038/54598162-de990780-4a2f-11e9-8c2e-43a400d88902.png)

**Comment by wordshaker** [comment]
This has happened for the two users using Internet Explorer version 11.0 (in case the browser version is needed)

**Comment by johnnolan** [comment]
This appears to be to do with a missing polyfill for assign.

`TypeError: Object doesn't support property or method 'assign'`

By default nextjs transpiles this for us, however this happens in the react-bootstrap library which is out of its control.

I have got a fix and will create a PR against this ticket
