### ISSUE TITLE
Feature Request: Add Cypress tests

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#550]
### Describe the feature

Add Cypress tests for the website

### Advantages

Decreases the chance of faulty releases

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Cypress tests for at least one page

**Comment by ivanELEC** [comment]
Contributing to this via [this branch](https://github.com/DDDEastMidlandsLimited/dddem-web/tree/e/add-cypress-tests)

**Comment by johnnolan** [comment]
@ivanELEC are you still wanting to complete this? I am happy to help you over Hacktober if you need a hand and pairing on it?

**Comment by ivanELEC** [comment]
Hi @johnnolan - thanks for the offer! This ended up moving to the backburner and ended up getting fried to a crisp entirely! The feature request you added in is a great idea so will pick this back up and also rectify the request
