### ISSUE TITLE
Enhancement: Make the DDD Website extensible to other DDD Events

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#57]
### Describe the feature

Currently, the colour theme for DDD East Midlands is in the theme.js and is configurable. It would be great if this could extend to logo and copy for other DDD events to fork the repository and apply it to their own event with ease.

There are a number of options:

* New repository based on this current repository for other DDD events to fork with easy configuration **(preferred)**

* Centralise this kind of configuration on the main site

However it's approached, use for others should be well documented. 

### Advantages

* Other DDD Events can use our site framework with ease (but with different colour scheme) and be consistent with our type of branding if they wish.

#### Acceptance Criteria

- [ ] Colour theme centrally configurable (see theme.js)
- [ ] Logo centrally configuarable
- [ ] Reference to DDD <place name> configurable
- [ ] Well documented for use.

**Comment by wordshaker** [comment]
@johnnolan - I will probably direct any questions around this to you.

**Comment by wordshaker** [comment]
If anyone wishes to pick up this issue, best to contact me directly for further details, having a repository set up etc. Please @ me.

**Comment by piratelicorne** [comment]
Hi.. what do you mean by "other DDD Events can use our site.." , what are "DDD Events" other sites?

**Comment by wordshaker** [comment]
There are many conferences that are under the "DDD" umbrella. This task would be to move the logo, colour scheme and name of event to a centralised location so the other events could use this code base to spin up their own DDD websites
