### ISSUE TITLE
HELP WANTED: Upgrade to use NextJS 12

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#673]
### Describe the feature

[NextJS 12](https://nextjs.org/blog/next-12) requires a change in this sites configuration to be ESLint compatible and no longer use Babel. We could do with the help of some SUPER javascript developers to port us across

### Advantages
- We get the many advantages of the new NEXT version
- Future maintenance and patches will be easier

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Project builds on NextJS 12

**Comment by wordshaker** [comment]
@johnnolan @ivanELEC I could use your help and wisdom on this one

**Comment by johnnolan** [comment]
Ooh this looks tasty, will pick this up tomorrow and see how far I get :)

**Comment by johnnolan** [comment]
[x]  npm-upgrade all dependencies - Done
[ ] Alter any eslint and babel config to work properly with new package names
[ ] Update node build to 14 or 17

**Comment by johnnolan** [comment]
This is now ready for review here #674
