### ISSUE TITLE
Feature Request: Add auto merge of dependabot updates

### ISSUE THREAD

**Issue by johnnolan** [DDDEastMidlandsLimited/dddem-web#806]
### Describe the feature

Currently the site gets a lot of dependabot PRs due to its JS nature.

This will add a workflow that if the tests pass will auto merge the requests for us.

An example of the workflow is here https://github.com/johnnolan/wild-magic-surge-5e/tree/main/.github/workflows

### Advantages

Less time clicking merge buttons each morning.

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

PRs from dependabot are auto merged if tests pass - [ ]

**Comment by johnnolan** [comment]
@wordshaker what are your thoughts? Are you confident enough in the testing to do this?

**Comment by wordshaker** [comment]
Haha dang, this will stop my GitHub from looking so healthy and active 😂

**Comment by johnnolan** [comment]
Wicked, will have a play tonight and tag ya when ready!

**Comment by johnnolan** [comment]
Ready for review when you are bored at some point!
