### ISSUE TITLE
Bug: Automatically compress images as part of CI/CD pipeline

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#849]
### Describe the bug

Images aren't automatically compressed on deployment and as such some take a lot of time to load

**To Reproduce**

Steps to reproduce the behaviour:

1. View image size

**Reproduces how often:**

N/A

**Expected behaviour**

Images are compressed in an automated fashion

**Screenshots**

N/A

**Comment by johnnolan** [comment]
Taking this one as I already do this elsewhere and can have it done this week.
