### ISSUE TITLE
Img elements do not have alt attributes

### ISSUE THREAD

**Issue by shzwlkr** [DDDEastMidlandsLimited/dddem-web#97]
### Describe the feature
Creating this off the back of a Lighthouse audit that was ran for #50. 
 
Certain images don't have alt text which isn't great for accessibility. Proposing an enhancement to add some alt text descriptions to images where sensible. 

### Advantages

* Makes the site more accessible. 

#### Acceptance Criteria
- [ ] Images across the site have an alt tag with a sensible description to help users that rely on screen readers.

**Comment by wordshaker** [comment]
Been done by #98
