### ISSUE TITLE
Bug: Fix Pa11y Timeout Error

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-web#970]
### Describe the bug

Fix Pa11y timeout issues and re-enable in the test and build workflow

**To Reproduce**

Steps to reproduce the behaviour:

1. Add the following to the test workflow

```
- name: Run pa11y
        run: npm run pa11y
```

2. Run test and build workflow

**Reproduces how often:**

100% of the time

**Expected behaviour**

Pally runs and does not timeout

**Screenshots**

![image](https://user-images.githubusercontent.com/13496774/205503591-37b825a1-6df2-4480-890d-20c5dccdafc9.png)

**Comment by johnnolan** [comment]
Have built a new way to handle this on other projects that is cleaner and faster, will implement here soon
